export const CELL_CLICK = 'CELL_CLICK';
export const GAME_SELECT = 'GAME_SELECT';
export const GAME_START = 'GAME_START';
export const CELL_EXPLOSION_FRAGMENT = 'CELL_EXPLOSION_FRAGMENT';
export const LAST_LETTER_FOUND = 'LAST_LETTER_FOUND';